export const companies = [
    { text: `Tutte` },
    { text: `Mahindra` },
    { text: `Alfa Romeo` },
    { text: `Mazda` },
    { text: `Alpine` },
    { text: `Mercedes` },
    { text: `Aston Martin` },
    { text: `Mg` },
    { text: `Audi` },
    { text: `Mini` },
    { text: `Bmw` },
    { text: `Mitsubishi` },
    { text: `Citroen` },
    { text: `Nissan` },
    { text: `Cupra` },
    { text: `Opel` },
    { text: `Dacia` },
    { text: `Peugeot` },
    { text: `Ds` },
    { text: `Porsche` },
    { text: `Dr` },
    { text: `Renault` },
    { text: `Fiat` },
    { text: `Seat` },
    { text: `Ford` },
    { text: `Skoda` },
    { text: `Honda` },
    { text: `Ssangyong` },
    { text: `Hyundai` },
    { text: `Subaru` },
    { text: `Jaguar` },
    { text: `Suzuki` },
    { text: `Jeep` },
    { text: `Toyota` },
    { text: `Kia` },
    { text: `Tesla` },
    { text: `Lancia` },
    { text: `Volkswagen` },
    { text: `Land Rover` },
    { text: `Volvo Xev` },
    { text: `Lexus` },
  ];